name: Release
on: 
  push:
    branches: 
      - master
      
jobs:
  release:
    if: |
      github.event_name == 'push' )
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: PSScriptAnalyzer tests
      shell: pwsh
      run: |
        Get-ChildItem $env
    # - uses: "marvinpinto/action-automatic-releases@latest"
    #   with:
    #     title: "${{ github.ref_name }}"
    #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
    #     prerelease: false
