name: Release
on: 
  push:
    tags: 
      - 'v[0-9]+.[0-9]+.[0-9]+'
      
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: PSScriptAnalyzer tests
      shell: pwsh
      run: |
        Get-ChildItem env:
