name: Release
on: 
  push:
    tags: 
      - 'v[0-9]+.[0-9]+.[0-9]+'
      
jobs:
  release:
    if: |
      github.actor == '1stewart' 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        name: "${{ github.ref_name }}"