name: Release
on: 
  push:
    branches: 
      - master
      
jobs:
  release:
    if: |
      github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: PSScriptAnalyzer tests
      shell: pwsh
      run: |
        Get-ChildItem $env
