name: Release
on: 
  push:
    branches: 
      - master
    tags:
      - v*
      
jobs:
  release:
    if: |
      github.event_name == 'push' && startsWith(github.ref_name ,'v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
